<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 .\watch.gltf -T -t -s
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers, useFrame } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }
  
  export const ref = new Group()
  let time = 0
  let secRot = [0, Math.PI*2, 0];
  let minRot = [0, 0, 0];
  let hourRot = [-Math.PI, 0, -Math.PI];
  useFrame(({ camera }, delta)=>{
    time += delta
    secRot[1]=time*(Math.PI/6)
    minRot[1]=secRot[1]/60
    hourRot[1]=minRot[1]/60

  })
  type GLTFResult = {
    nodes: {
      base: THREE.Mesh
      Cube: THREE.Mesh
      Cube001: THREE.Mesh
      Cube002: THREE.Mesh
      Cylinder: THREE.Mesh
      Cylinder001: THREE.Mesh
      Cylinder002: THREE.Mesh
      Plane: THREE.Mesh
      Plane001: THREE.Mesh
    }
    materials: {
      ['Material.003']: THREE.MeshStandardMaterial
      ['Material.002']: THREE.MeshStandardMaterial
      ['Material.007']: THREE.MeshStandardMaterial
      ['Material.001']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/watch-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh castShadow receiveShadow geometry={gltf.nodes.base.geometry} material={gltf.materials['Material.003']} />
    <!-- عقرب الثواني -->
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube.geometry}
      material={gltf.materials['Material.002']}
      position={[0, 0.07, 0]}
      rotation={secRot}
      scale={[0.27, 0.4, 0.13]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube001.geometry}
      material={gltf.materials['Material.003']}
      position={[0.29, 0, 0.35]}
      rotation={[0, -0.37, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube002.geometry}
      material={gltf.materials['Material.007']}
      position={[0, -0.7, 0]}
      scale={[5.41, 0.65, 5.41]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder.geometry}
      material={gltf.materials['Material.002']}
      position={[0.39, 0, 0.22]}
      rotation={[0, -Math.PI / 6, -Math.PI / 2]}
      scale={0.65}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder001.geometry}
      material={gltf.materials['Material.001']}
      position={[0, 0.03, 0]}
      scale={[1.07, 1.23, 1.07]}
    />
    <!--عقرب الدقائق -->

    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder002.geometry}
      material={gltf.materials['Material.002']}
      position={[0.45, 0, 0]}
      rotation={[0, 0, -Math.PI / 2]}
      scale={0.75}
    />
    <!--عقرب الدقائق -->

    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane.geometry}
      material={gltf.materials['Material.002']}
      position={[0, 0.06, 0]}
      rotation={minRot}
      scale={0.02}
    />
    <!--عقرب الساعات -->
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane001.geometry}
      material={gltf.materials['Material.002']}
      position={[0, 0.05, 0]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={0.02}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
